S02 us3 carousel
WildCodeSchool/orleans-0919-php-magasinbleu pull request #45
Opened 2019-11-05 16:27 UTC by Tenkho

2019-11-05 20:27 UTC, sdesousa approved these changes

2019-11-05 22:31 UTC, sblondeau requested changes

2019-11-05 22:31 UTC, sblondeau commented on public/assets/css/Home/carousel.css
> +    color: white;
variable CSS pour toutes les couleurs ! un var(--light) par exemple

2019-11-05 22:31 UTC, sblondeau commented on public/assets/css/Home/carousel.css
> +    background-color: rgba(0, 0, 0, 0.3);
idem

2019-11-05 22:31 UTC, sblondeau commented on public/assets/css/Home/carousel.css
> +@media screen and (max-width: 980px)
pas de media query pour ça. tu as des classes bootstrap d-md-none par exemple
https://getbootstrap.com/docs/4.3/utilities/display/#notation

2019-11-06 15:21 UTC, sblondeau approved these changes

2019-11-06 15:21 UTC, merged