S02 us03 lastproducts
WildCodeSchool/orleans-0919-php-magasinbleu pull request #46
Opened 2019-11-05 17:17 UTC by Niagaraa

Affichage des derniers produits

2019-11-06 20:14 UTC, sdesousa approved these changes

2019-11-07 14:15 UTC, sblondeau requested changes

2019-11-07 14:15 UTC, sblondeau commented on src/Model/ProductManager.php
> +    public function selectAll(): array
j'appelerais la méthode lastProduct() c'est beaucoup plus parlant, car là j'ai mis du temps à comrpendre ce que vous vouliez faire

et à la place du LIMIT 3, je mettrais une LIMIT ' . self::NB_LAST_PRODUCTS
tu places la constante en haut de fichier et tu lui donnes la valeur 3. C'est plus propre que de mettre "3" en dur et plus facile à modifier si besoin.

2019-11-07 14:15 UTC, sblondeau commented on public/assets/css/Home/lastproducts.css
> +@media screen and (max-width: 768px) {
je veux pas vous faire perdre trop de temps mais je suis sûr que vous pourriez vous passer de cette media query...

2019-11-07 19:12 UTC, sdesousa approved these changes

2019-11-07 21:42 UTC, sblondeau approved these changes

2019-11-07 21:42 UTC, merged