S01 us1 navbar
WildCodeSchool/orleans-0919-php-magasinbleu pull request #48
Opened 2019-11-06 17:00 UTC by Oxy-Romain

2019-11-06 20:03 UTC, sdesousa requested changes
Tu as une ligne en double

2019-11-06 20:08 UTC, sdesousa requested changes

2019-11-06 20:08 UTC, sdesousa commented on public/assets/css/Home/mapHours.css
> +.hours{
Plusieurs class vide, tu peut les retirer

2019-11-06 20:08 UTC, sdesousa commented on public/assets/css/Home/index.css
> +@import "nav.css";
Ligne en double

2019-11-07 11:02 UTC, sdesousa approved these changes

2019-11-07 15:15 UTC, sblondeau requested changes

2019-11-07 15:15 UTC, sblondeau commented on src/View/Home/mapHours.html.twig
> +            <h5 class="card-title card-title-hours">Horraires</h5>
on y était presque... ;-)

2019-11-07 19:07 UTC, sdesousa approved these changes

2019-11-07 21:43 UTC, sblondeau approved these changes

2019-11-08 12:45 UTC, merged