S02 us05 filter
WildCodeSchool/orleans-0919-php-magasinbleu pull request #64
Opened 2019-11-12 17:08 UTC by sdesousa

2019-11-12 17:24 UTC, Niagaraa approved these changes

2019-11-12 17:24 UTC, Niagaraa commented on public/assets/css/Home/universe.css
> +}
Une hauteur définie deux fois

2019-11-12 21:01 UTC, Niagaraa approved these changes

2019-11-12 21:31 UTC, sblondeau requested changes

2019-11-12 21:31 UTC, sblondeau commented on src/Controller/ProductController.php
>          $countPages = (int)($countProducts/12+1);
remplace là aussi 12 par self::PRODUCTS_BY_PAGES

2019-11-12 21:31 UTC, sblondeau commented on src/Model/BrandManager.php
> +                    JOIN ' . $this->table . ' b ON p.brand_id = b.id
self::TABLE pour etre cohérent

2019-11-12 21:31 UTC, sblondeau commented on src/Model/ProductManager.php
> +        $statement->bindValue('brand', $filterPage['brand'], \PDO::PARAM_STR);
je préfère que tu enlèves le "%" en param par défaut de la méthode dans le controlleur, et qu'ici tu mettes $filterPage['brand'] ?? '%', ce n'est pas le rôle du controlleur de gérer la valeur par défaut de la requete SQL., idem pour les categories

2019-11-12 21:31 UTC, sblondeau commented on src/Model/ProductManager.php
>      const TABLE_UNIVERSE = 'universe';
plutot que de créer une constante TABLE_UNIVERSE dans tous les manager, créer un UniversManager (meme s'il n'est pas utilisé pour autre chose) serait sans doute plus propre.

2019-11-12 21:31 UTC, sblondeau commented on src/View/Product/index.html.twig
> +                       "{{ urlStart ~ actualFilter.universe ~
hum... ça doit sans doute fonctionner, mais ce n'est pas la bonne façon de faire, car ton URL va devenir très compliquée à gérer si tu as 25 critères de tri différents... une meilleure approche pour tout ce qui est filtre comme ça, est de passer plutôt par des query strings... idéalement, mais on peut en rediscuter si tu veux

2019-11-14 08:27 UTC, Niagaraa approved these changes

2019-11-14 10:08 UTC, sblondeau requested changes

2019-11-14 10:08 UTC, sblondeau commented on src/Controller/ProductController.php
> +        $filterPage['universe'] = (strpos($universe, '?'))
je ne comprends pas ce que tu veux faire la

2019-11-14 10:08 UTC, sblondeau commented on src/Controller/ProductController.php
> +        $filterPage['universe'] = (strpos($universe, '?'))
si c'est un pb de route, c'est peut etre qu'il te manque un "/" après universe, essaie la route
product/indexUniverse/universe/?brand=...

2019-11-14 10:08 UTC, sblondeau commented on src/Controller/ProductController.php
> +        if (isset($_GET['brand'])) {
simplifie avec 
```
$filterPage = [
    'universe' => $universe,
    'brand' => $_GET['brand'] ?? null,
    'category' => $_GET['category'] ?? null,
```

2019-11-14 10:08 UTC, sblondeau commented on src/Controller/ProductController.php
> +        $pageNumber = (strpos($page, '?')) ? substr($page, 0, strpos($page, '?')) : $page;
idem

2019-11-14 14:26 UTC, Niagaraa approved these changes

2019-11-14 15:17 UTC, sblondeau approved these changes

2019-11-14 15:32 UTC, Niagaraa approved these changes

2019-11-14 16:15 UTC, merged