delete + fix affichage dernier produits
WildCodeSchool/orleans-0919-php-magasinbleu pull request #69
Opened 2019-11-14 16:04 UTC by Niagaraa

2019-11-14 16:23 UTC, ghost approved these changes

2019-11-15 08:24 UTC, sblondeau approved these changes

2019-11-15 08:25 UTC, sblondeau requested changes

2019-11-15 08:25 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +        $productManager = new ProductManager();
if REQUEST_METHOD == POST !

2019-11-15 08:25 UTC, sblondeau commented on src/View/AdminProduct/index.html.twig
> +                <a class="btn btn-danger" href="/AdminProduct/delete/{{ product.id }}"
en POST le delete, il me faut un form ici !

2019-11-15 09:17 UTC, sdesousa approved these changes

2019-11-15 10:04 UTC, sblondeau approved these changes

2019-11-15 10:04 UTC, merged